title: Zhipeng Fan # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  3rd Year Ph.D. student at NYU ECE; Enthusiastic about 3D Computer Vision and video understanding
  <br><br>
  <a href="https://zhipeng-fan.github.io/">Projects</a>
  <br><br>
  <a href="https://zhipeng-fan.github.io/posts">Posts</a>
  <br><br>
  <a href="https://zhipeng-fan.github.io/pdf/Zhipeng_Fan_Resume.pdf">Resume</a>
  
google_analytics: UA-155296425-1 # your Google Analytics tracking ID here
